name: home-assistant-snap
version: '0.116.2'
summary: Open source home automation that puts local control and privacy first
description: |
  Home Assistant is a home automation platform running on Python 3. 
  It is able to track and control all devices at home and offer a 
  platform for automating control.

  Please see official docs: https://git.giaever.org/joachimmg/home-assistant-snap
base: core20
grade: stable
confinement: strict
license: Apache-2.0

layout:
  /etc/pip.conf:
    bind-file: $SNAP_DATA/pip.conf
  /etc/openzwave:
    bind: $SNAP/openzwave

slots:
  components:
    interface: content
    content: components
    write: 
      - $SNAP_DATA/custom_components
  certs:
    interface: content
    content: certs
    write: 
      - $SNAP_DATA/certs
  configurations:
    interface: content
    write:
      - $SNAP_DATA

hooks:
  install:
    plugs:
      - network
      - network-bind
  prepare-slot-certs:
    plugs:
      - network
      - network-bind

apps:
  home-assistant-snap:
    command: bin/hass --config $SNAP_DATA
    daemon: simple
    environment:
      PIP_USER: 1
    restart-condition: always
    plugs: 
      - bluez
      - network
      - network-bind
      - raw-usb
      # GPIO devices etc.. (e.g RaZberry GPIO hat)
      - physical-memory-control
    slots: 
      - components
  check-config:
    command: bin/hass --script check_config
  renew-cert:
    command: bin/certs-daemon
    daemon: oneshot
    restart-condition: always
    timer: 00:00-24:00/24
    slots:
      - certs
    plugs:
      - network
      - network-bind
  force-renew-cert:
    command: bin/certs-daemon
    slots:
      - certs
    plugs:
      - network
      - network-bind

parts:
  homeassistant:
    plugin: python-wot-plugin
    source: https://github.com/home-assistant/core.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    python-packages:
      - setuptools
      - wheel
      - Cython
      - pip
    build-packages:
      - python3
      - python3-dev
      - python3-setuptools
      - python3-wheel
      - pkg-config
      - autoconf
      - build-essential
      - cmake
      - cython3
      - ffmpeg
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libffi-dev
      - libglib2.0-dev
      - libglu1-mesa-dev
      - libgpiod-dev
      - libjpeg-dev
      - libopenzwave1.5-dev
      - libssl-dev
      - libswscale-dev
      - libudev-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
    stage-packages:
      - freeglut3
      - ffmpeg
      - libglu1-mesa
      - zlib1g
    requirements:
      - requirements_all.txt
    constraints:
      - homeassistant/package_constraints.txt
    override-build: |
      snapcraftctl build
      sed -i 's/include-system-site-packages = false/include-system-site-packages = true/g' $SNAPCRAFT_PART_INSTALL/pyvenv.cfg
  hooks:
    plugin: dump
    source: ./scripts/hooks
    source-type: local
    stage-packages:
      - uuid
      - libossp-uuid16
      - libassuan0
      - gpg
      - gpg-agent
    organize:
      install: snap/hooks/install
      configure: snap/hooks/configure
      post-refresh: snap/hooks/post-refresh
      prepare-slot-certs: snap/hooks/prepare-slot-certs
  bins:
    plugin: dump
    source: ./scripts/bin
    source-type: local
    organize:
      slot-certs: bin/slot-certs
      certs-daemon: bin/certs-daemon
  config:
    plugin: dump
    source: ./scripts/config
    source-type: local
