name: home-assistant-snap
version: '0.113.3'
summary: Open source home automation that puts local control and privacy first
description: |
    Home Assistant is a home automation platform running on Python 3. 
    It is able to track and control all devices at home and offer a 
    platform for automating control.
base: core20
grade: stable
confinement: strict
architectures:
  - build-on: [arm64, amd64, ppc64el]
layout:
  /etc/pip.conf:
    bind-file: $SNAP_DATA/pip.conf
  /etc/openzwave:
    bind: $SNAP/openzwave
apps:
  hass:
    command: bin/hass --config $SNAP_DATA
    daemon: simple
    environment:
      PIP_USER: 1
    restart-condition: always
    plugs: 
      - bluez
      - network
      - network-bind
      - raw-usb
      # GPIO devices etc.. (e.g RaZberry GPIO hat)
      - physical-memory-control
parts:
  homeassistant:
    plugin: python-wot-plugin
    source: https://github.com/home-assistant/core.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    python-packages:
      - setuptools
      - wheel
      - Cython
      - pip
        #- bcrypt
    build-packages:
      - python3
      - python3-dev
      - python3-setuptools
      - python3-wheel
      - pkg-config
      - autoconf
      - build-essential
      - cmake
      - cython3
      - ffmpeg
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libffi-dev
      - libglib2.0-dev
      - libglu1-mesa-dev
      - libjpeg-dev
      - libopenzwave1.5-dev
      - libssl-dev
      - libswscale-dev
      - libudev-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
    stage-packages:
      - freeglut3
      - ffmpeg
      # - libavcodec58
      # - libavdevice58
      # - libavfilter7
      # - libavformat58
      # - libavutil56
      # - libffi7
      # - libglib2.0-0
      - libglu1-mesa
      # - libjpeg8
      # - libopenzwave1.5
      # - libssl1.1
      # - libswscale5
      # - libudev1
      # - libswresample3
      # - libxml2
      # - libxslt1.1
      - zlib1g
    requirements:
      - requirements_all.txt
    constraints:
      - homeassistant/package_constraints.txt
    override-build: |
      snapcraftctl build
      sed -i 's/include-system-site-packages = false/include-system-site-packages = true/g' $SNAPCRAFT_PART_INSTALL/pyvenv.cfg
