name: home-assistant
version: git
summary: Open source home automation that puts local control and privacy first
description: |
    Home Assistant is a home automation platform running on Python 3. 
    It is able to track and control all devices at home and offer a 
    platform for automating control.
grade: devel
base: core20
confinement: devmode
apps:
  hass:
    command: bin/hass --config $SNAP_DATA
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
parts:
  homeassistant:
    plugin: python-wot-plugin
    source: https://github.com/home-assistant/core.git
    source-tag: 0.112.3
    #build-environment:
    #  - SNAPCRAFT_PYTHON_INTERPRETER: "python3.8"
    python-packages:
      - setuptools
      - wheel
      - Cython
    build-packages:
      - python3
      - python3-dev
      - pkg-config
      - autoconf
      - build-essential
      - libffi-dev
      - libglib2.0-dev
      - libjpeg-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - libudev-dev
      - zlib1g-dev
      - cython3
    stage-packages:
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libswscale-dev
      - libavresample-dev
      - libavfilter-dev
      - libglu1-mesa-dev
      - ffmpeg
    requirements:
      - requirements_all.txt
    constraints:
      - homeassistant/package_constraints.txt
