name: home-assistant-snap
version: '0.112.4'
summary: Open source home automation that puts local control and privacy first
description: |
    Home Assistant is a home automation platform running on Python 3. 
    It is able to track and control all devices at home and offer a 
    platform for automating control.
base: core20
grade: stable
confinement: strict
#architectures: 
#  - build-on: [arm64, armhf] #, armhf, amd64, ppc64el]
apps:
  hass:
    command: bin/hass --config $SNAP_DATA
    daemon: simple
    restart-condition: always
    plugs: 
      - bluez
      - network
      - network-bind

      # GPIO devices etc..
      - physical-memory-control
parts:
  homeassistant:
    plugin: python-wot-plugin
    source: https://github.com/home-assistant/core.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    #python-packages:
      #- urllib3[secure]
      #- setuptools
      #- wheel
      #- Cython
    build-packages:
      - python3
      - python3-dev
      - python3-setuptools
      - python3-wheel
      - pkg-config
      - autoconf
      - build-essential
      - cmake
      - cython3
      - ffmpeg
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libffi-dev
      - libglib2.0-dev
      - libglu1-mesa-dev
      - libjpeg-dev
      - libopenzwave1.5-dev
      - libssl-dev
      - libswscale-dev
      - libudev-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev

    requirements:
      - requirements_all.txt
    constraints:
      - homeassistant/package_constraints.txt
